version: '3'
services:
  app:
    build: ./
    user: root
    volumes:
      - ./:/app/src
    working_dir: /app/src
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888
